package clearcut;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.*;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import clearcut.Person;
import clearcut.PersonRepository;

@RestController
@Controller
@RequestMapping(path="/clearcut")
public class GreetingController {
  // This means to get the bean called personRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private PersonRepository personRepository;

  private static final String TEMPLATE = "Hello, %s!";

  @RequestMapping("/clearcut")
  public HttpEntity<Greeting> greeting(
          @RequestParam(value = "name", required = false, defaultValue = "Joe Bloggs") String name) {

          Greeting greeting = new Greeting(String.format(TEMPLATE, name));
          greeting.add(linkTo(methodOn(GreetingController.class).greeting(name)).withSelfRel());

          return new ResponseEntity<>(greeting, HttpStatus.OK);
  }

  @GetMapping(path="/add")     // Map ONLY GET Requests - clearcut/add
  public @ResponseBody String addNewPerson (@RequestParam String name) {
          Person n = new Person();
          n.setName(name);
          personRepository.save(n);
          return "Saved";
  }

  @GetMapping(path="/all")     // clearcut/all
  public @ResponseBody Iterable<Person> getAllPersons() {
          return personRepository.findAll();
  }
}
